version: "3"
services:
    node-devops:
        image: labidouille/devops
        build: .
        ports:
            - "4000:4000"
        environment:
            - DB=mongodb://mongo:27017/todo
        depends_on:
            - mongo
        volumes:
            - ./:/usr/src/app
    mongo:
        image: mongo
        ports:
            - "27017:27017"
